title: David O’Neal – GRC & Security Engineering Portfolio
description: grc, cybersecurity, aws, portfolio, risk-management
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-seo-tag
github:
  is_project_page: false
author: David O’Neal
