name: Link Check
on:
  push:
    paths:
      - 'docs/**/*.md'
      - 'docs/**/*.html'
      - '.lychee*'
      - '.github/workflows/link-check.yml'
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --base "https://doneal78.github.io/grc_portfolio/"
            --verbose
            --exclude-mail
            --exclude-loopback
            docs/**/*.md
            docs/**/*.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
